version: 2.1
jobs:
  Linux_1:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      HOST: x86_64-unknown-linux-gnu
      BUILD_PACKAGES: "build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3"
      PACKAGES: "python3-zmq qtbase5-dev qttools5-dev-tools libdbus-1-dev libharfbuzz-dev"
      CONFIG: "--enable-zmq --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-debug CFLAGS=\"-g0 -O2 -funsigned-char\" CXXFLAGS=\"-g0 -O2 -funsigned-char\""
    steps:
      - run:
          name: Prepare build environment
          command: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends --no-upgrade -qq $$BUILD_PACKAGES $PACKAGES
      - checkout
      - run:
          name: Phase 1 (autogen)
          command: ./autogen.sh
      - run:
          name: Phase 2 (configure)
          command: ./configure $CONFIG
      - run:
          name: Phase 3 (build)
          command: make

workflows:
  version: 2
  Go_Live:
    jobs:
      - Linux_1
